Print errors

diff --git a/uur b/uur
--- a/uur
+++ b/uur
@@ -6,14 +6,14 @@ function install(){
   package="$1"
   package_realpath="$(realpath $package)"
   cd "$uur_data_path"
-  bash "$package_realpath/make"
+  draw_spinner "Installing \"$package\"" "bash "$package_realpath/make""
   cd "$SCRIPTPATH"
 }
 
-set -o errexit      # Exit on most errors (see the manual)
-set -o nounset      # Disallow expansion of unset variables
-set -o pipefail     # Use last non-zero exit code in a pipeline
-set -o errtrace     # Ensure the error trap handler is inherited
+# set -o errexit      # Exit on most errors (see the manual)
+# set -o nounset      # Disallow expansion of unset variables
+# set -o pipefail     # Use last non-zero exit code in a pipeline
+# set -o errtrace     # Ensure the error trap handler is inherited
 
 SCRIPT=$(readlink -f "$0")
 SCRIPTPATH=$(dirname "$SCRIPT")
@@ -31,11 +31,11 @@ case $1 in
     packages=($(ls))
     for package in "${packages[@]}" ; do
       [ -d "$package" ] || continue
-      draw_spinner "Installing \"$package\"" "install "$package""
+      install "$package"
     done
     ;;
   install)
     sudo -v
-    draw_spinner "Installing \"$2\"" "install "$2""
+    install "$2"
     ;;
 esac
